apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: workscheduleexport-ingress
    annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
    rules:
        - host: workscheduleexport.cederholm.fi
          http:
            paths:
                - path: /
                  backend:
                    serviceName: workscheduleexport-service
                    servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
    name: workscheduleexport-service
spec:
    ports:
        - port: 80
          protocol: TCP
    selector:
        app: workscheduleexport

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: workscheduleexport-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: workscheduleexport
    template:
        metadata:
            labels:
                app: workscheduleexport
        spec:
            containers:
                - name: workscheduleexport
                  image: cloud.canister.io:5000/johnnyhansson/workscheduleexport:1
                  env:
                    - name: ASPNETCORE_URLS
                      value: http://*:80
            imagePullSecrets:
                - name: canister